local Engine = require("grid.engine")
local Shared = require("grid.shared")
local Session = require("grid.session")
local area = { x = 0, y = 38, w = 1000, h = 800 }

local function fixture()
    local e = Engine.new({ row_gap = 48 })
    for i, key in ipairs({ "a", "b", "c", "d" }) do
        e:set_tile("1", key, { x = ((i - 1) % 2) * 500, y = i > 2 and 848 or 0, w = 500, h = 800 })
    end
    local s = e:sync("1", {{key="a", active=true}, {key="b"}, {key="c"}, {key="d"}}, area)
    local other = e:sync("2", {{key="local", active=true}}, area)
    return e, Shared.new(e), s, other
end

return function(T)
    T.case("a workspace containing only shared rows retains an empty local row", function()
        local e, shared, s = fixture()
        shared:toggle(s)
        e:focus(s, "down")
        shared:toggle(s)
        T.truthy(s.empty_row)
        T.near(s.empty_row.y, s.rows[#s.rows].y + s.rows[#s.rows].height + 48)
        T.near(s.empty_row.height, area.h)
        T.falsy(s.empty_row.selected)
    end)

    T.case("empty local row accepts focus without retaining an offscreen window selection", function()
        local e, shared, s = fixture()
        shared:toggle(s)
        e:focus(s, "down")
        e:pan(s, "right", 117)
        shared:toggle(s)
        local result = e:command(s, "focus down")
        T.truthy(result.clear_focus)
        T.falsy(s.focus_key)
        T.falsy(e:_anchor_location(s))
        T.near(s.viewport.y, s.empty_row.y)
        e:sync("1", {{key="a"},{key="b"},{key="c",active=true},{key="d"}}, area)
        shared:refresh()
        T.truthy(s.empty_row.selected)
        T.falsy(s.focus_key)
        T.falsy(e:move(s, "down"))
        local up = e:command(s, "focus up")
        T.equal(up.focus_key, "c")
        T.near(s.viewport.x, 117)
    end)

    T.case("a new window fills the empty row locally and closing it restores the slot", function()
        local e, shared, s = fixture()
        shared:toggle(s)
        e:focus(s, "down")
        shared:toggle(s)
        e:focus(s, "down")
        local y = s.empty_row.y
        e:sync("1", {{key="a"},{key="b"},{key="c"},{key="d"},{key="local",active=true}}, area)
        shared:refresh()
        T.falsy(s.empty_row)
        T.near(s.tiles["local"].y, y)
        T.equal(s.focus_key, "local")
        for _, record in pairs(shared.rows) do T.truthy(record.row_id ~= s.tiles["local"].row_id) end
        e:forget_window("local")
        shared:refresh()
        T.truthy(s.empty_row)
        T.near(s.empty_row.y, y)
    end)

    T.case("sharing a lower row promotes it above local rows without changing focus or pan", function()
        local e, shared, s, other = fixture()
        e:focus(s, "down")
        e:pan(s, "right", 137)
        local key = s.focus_key
        local screen_y = s.tiles[key].y - s.viewport.y
        shared:toggle(s)
        T.equal(s.rows[1].id, s.tiles.c.row_id)
        T.equal(s.focus_key, key)
        T.near(s.tiles[key].y - s.viewport.y, screen_y)
        T.near(s.viewport.x, 137)
        shared:transfer(shared:pending("2")[1], other)
        T.equal(other.rows[1].id, other.tiles.c.row_id)
        T.truthy(other.tiles.c.y < other.tiles["local"].y)
        T.truthy(e:validate(other))
    end)

    T.case("shared rows stay above new local rows in both scroll modes", function()
        for _, mode in ipairs({"rows", "shared"}) do
            local e, shared, s = fixture()
            shared:toggle(s)
            e:set_scroll_mode(s, mode)
            e:command(s, "insert up")
            e:sync("1", {{key="a",active=true},{key="b"},{key="c"},{key="d"},{key="above"}}, area)
            shared:refresh()
            T.equal(s.rows[1].id, s.tiles.a.row_id)
            T.truthy(s.tiles.a.y < s.tiles.above.y)
            T.truthy(e:validate(s))
        end
    end)

    T.case("shared row transfers real ownership with scroll and geometry intact", function()
        local e, shared, s, other = fixture()
        e:pan(s, "right", 271)
        T.truthy(shared:toggle(s).shared)
        local record = shared:pending("2")[1]
        local local_y = other.tiles["local"].y - other.viewport.y
        shared:transfer(record, other)
        T.falsy(s.tiles.a)
        T.equal(record.workspace_id, "2")
        T.equal(other.focus_key, "local")
        T.near(other.tiles["local"].y - other.viewport.y, local_y)
        T.near(other.row_views[other.tiles.a.row_id].x, 271)
        T.near(other.tiles.b.x - other.tiles.a.x, 500)
        T.near(other.tiles.b.w, 500)
        T.near(s.tiles.c.y, 0)
        T.truthy(e:validate(s))
        T.truthy(e:validate(other))
        shared:transfer(record, s)
        T.equal(s.rows[1].cells[1].key, "a")
        T.near(s.tiles.c.y, 848)
        T.near(s.row_views[s.tiles.a.row_id].x, 271)
        T.truthy(e:validate(s))
        T.truthy(e:validate(other))
    end)

    T.case("sharing supports scopes and unsharing leaves windows in current workspace", function()
        local _, shared, s, other = fixture()
        T.truthy(shared:toggle(s, "on", "1,2").shared)
        T.equal(#shared:pending("3"), 0)
        local record = shared:pending("2")[1]
        shared:transfer(record, other)
        other.focus_key = "a"
        T.falsy(shared:toggle(other).shared)
        T.equal(#shared:pending("1"), 0)
        T.truthy(other.tiles.a)
        T.falsy(shared:toggle(other, "on", "1,,2"))
        T.falsy(shared:toggle(other, "on", "1,3"))
        T.falsy(shared:toggle(other, "on", "0,2"))
        T.falsy(shared:toggle(other, "invalid"))
    end)

    T.case("empty destination focuses shared row without resetting horizontal pan", function()
        local e, shared, s = fixture()
        e:pan(s, "right", 219)
        shared:toggle(s)
        local empty = e:workspace("3", area)
        shared:transfer(shared:pending("3")[1], empty)
        T.equal(empty.focus_key, "a")
        T.near(empty.viewport.x, 219)
        T.near(empty.tiles.a.y, 0)
    end)

    T.case("shared row membership follows insertion moves and closure", function()
        local e, shared, s, other = fixture()
        shared:toggle(s)
        local record = shared:pending("2")[1]
        e:sync("1", {{key="a",active=true},{key="b"},{key="c"},{key="d"},{key="new"}}, area)
        e:move(s, "down") -- a leaves the shared row
        shared:transfer(record, other)
        T.truthy(s.tiles.a)
        T.falsy(other.tiles.a)
        T.truthy(other.tiles.b)
        T.truthy(other.tiles.new)
        e:forget_window("b")
        shared:refresh()
        T.equal(#shared:pending("1"), 1)
        e:forget_window("new")
        shared:refresh()
        T.equal(#shared:pending("1"), 0)
    end)

    T.case("multiple shared rows keep order and source focus over repeated transfers", function()
        local e, shared, s, other = fixture()
        shared:toggle(s)
        e:focus(s, "down")
        shared:toggle(s)
        for n = 1, 8 do
            local destination = n % 2 == 1 and other or s
            for _, record in ipairs(shared:pending(destination.id)) do shared:transfer(record, destination) end
            T.truthy(e:validate(s))
            T.truthy(e:validate(other))
            T.truthy(destination.tiles.a.y < destination.tiles.c.y)
            T.near(destination.tiles.c.y - destination.tiles.a.y, 848)
        end
    end)

    T.case("shared transfer checkpoint restores both ownership and layout after failure", function()
        local _, shared, s, other = fixture()
        shared:toggle(s)
        local saved = shared:checkpoint()
        shared:transfer(shared:pending("2")[1], other)
        shared:rollback(saved)
        T.truthy(shared.engine.workspaces["1"].tiles.a)
        T.falsy(shared.engine.workspaces["2"].tiles.a)
        T.equal(shared:pending("2")[1].workspace_id, "1")
    end)

    T.case("reload state restores shared membership scopes geometry and pan", function()
        local e, shared, s = fixture()
        e:pan(s, "right", 167)
        shared:toggle(s, "on", "1,2")
        local restored = Shared.new(Engine.new({ row_gap = 48 }))
        restored:rollback(Session.decode(Session.encode(shared:checkpoint())))
        T.equal(restored:pending("2")[1].scope, "1,2")
        T.near(restored.engine.workspaces["1"].viewport.x, 167)
        T.near(restored.engine.workspaces["1"].tiles.c.y, 848)
        T.truthy(restored.engine:validate(restored.engine.workspaces["1"]))
        local path = os.tmpname()
        Session.write(path, shared:checkpoint())
        T.truthy(Session.read(path).rows[1])
        T.falsy(Session.read(path), "reload state should be consumed once")
    end)

    T.case("reload state rejects truncation malformed numbers and executable content", function()
        for _, value in ipairs({"return os.execute('false')", "grid-session-v1\ns100:short", "grid-session-v1\nnnan;", "grid-session-v1\nt1:s1:x", "grid-session-v1\nb2"}) do
            T.falsy(pcall(Session.decode, value))
        end
    end)
end
